// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package go_micro_srv_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 托运结果
type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0xc6, 0xe9, 0xfe, 0xd7, 0x45, 0xa0, 0xe5, 0x00, 0x11, 0x1c, 0xa8, 0x8a, 0x90, 0x76, 0xea,
	0x61, 0x3c, 0x42, 0x0f, 0xa8, 0xd7, 0xee, 0x01, 0x60, 0x24, 0x56, 0x67, 0x89, 0x26, 0x55, 0x92,
	0x8d, 0x57, 0x83, 0xb7, 0x43, 0x4b, 0x57, 0x08, 0x42, 0x43, 0xbb, 0xf5, 0xb3, 0xfd, 0xd9, 0x3f,
	0xbb, 0x81, 0xb9, 0xd0, 0xca, 0x52, 0xad, 0x1a, 0x54, 0x2e, 0x6f, 0x8d, 0x76, 0x9a, 0xf1, 0x5a,
	0xe7, 0x0d, 0x09, 0xa3, 0x73, 0x6b, 0x76, 0x79, 0x90, 0xcf, 0x3e, 0x23, 0x48, 0x8a, 0x1f, 0xcd,
	0x2e, 0x60, 0x40, 0x92, 0x47, 0x69, 0xb4, 0x88, 0xab, 0x01, 0x49, 0x96, 0x42, 0x22, 0xd1, 0x0a,
	0x43, 0xad, 0x23, 0xad, 0xf8, 0xc0, 0x27, 0xc2, 0x10, 0xbb, 0x82, 0xc9, 0x3b, 0x52, 0xbd, 0x71,
	0x7c, 0x98, 0x46, 0x8b, 0x71, 0x75, 0x50, 0xac, 0x00, 0x10, 0x5a, 0xb9, 0x35, 0x29, 0x34, 0x96,
	0x8f, 0xd2, 0xe1, 0x22, 0x59, 0xde, 0xe7, 0xc7, 0x40, 0xf2, 0xa2, 0xaf, 0xad, 0x02, 0x1b, 0xbb,
	0x85, 0x78, 0x87, 0xd6, 0xe2, 0xdb, 0x33, 0x49, 0x3e, 0xf6, 0xc3, 0x67, 0x5d, 0xa0, 0x94, 0x59,
	0x03, 0xf1, 0xb7, 0xeb, 0x0f, 0xf8, 0x1d, 0x24, 0x62, 0x6b, 0x9d, 0x6e, 0xd0, 0xec, 0xbd, 0x1d,
	0x38, 0xf4, 0xa1, 0x52, 0xee, 0xb9, 0xb5, 0xa1, 0x9a, 0x94, 0xe7, 0x8e, 0xab, 0x83, 0x62, 0xd7,
	0x30, 0xdd, 0xda, 0xce, 0x34, 0xea, 0x12, 0x7b, 0x59, 0xca, 0xec, 0x23, 0x82, 0x59, 0x85, 0xb6,
	0xd5, 0xca, 0x22, 0xe3, 0x30, 0x15, 0x06, 0xd7, 0x0e, 0xbb, 0x99, 0xb3, 0xaa, 0x97, 0xec, 0x09,
	0x92, 0x60, 0x2f, 0x3f, 0x38, 0x59, 0x3e, 0xfc, 0xbb, 0x78, 0xff, 0x5d, 0x85, 0x4e, 0x56, 0xc2,
	0x79, 0x20, 0x2d, 0x1f, 0xfa, 0x13, 0x9e, 0xd8, 0xe9, 0x97, 0x75, 0x69, 0xe1, 0x72, 0xb5, 0xa1,
	0xb6, 0x25, 0x55, 0xaf, 0xd0, 0xec, 0x48, 0x20, 0x7b, 0x81, 0x79, 0xe1, 0x89, 0xc3, 0xbf, 0x7f,
	0x5a, 0xf3, 0x9b, 0xec, 0x78, 0x59, 0x7f, 0xa0, 0xec, 0xec, 0x75, 0xe2, 0xdf, 0xde, 0xe3, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x64, 0x56, 0x6f, 0x90, 0x02, 0x00, 0x00,
}
