// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_ALLOW Action = 0
	Action_DENY  Action = 1
	Action_CHILL Action = 2
)

var Action_name = map[int32]string{
	0: "ALLOW",
	1: "DENY",
	2: "CHILL",
}

var Action_value = map[string]int32{
	"ALLOW": 0,
	"DENY":  1,
	"CHILL": 2,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

type SomeMsg struct {
	Do                   Action   `protobuf:"varint,1,opt,name=do,proto3,enum=proto.Action" json:"do,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeMsg) Reset()         { *m = SomeMsg{} }
func (m *SomeMsg) String() string { return proto.CompactTextString(m) }
func (*SomeMsg) ProtoMessage()    {}
func (*SomeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_13a9f1b5947140c8, []int{0}
}

func (m *SomeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeMsg.Unmarshal(m, b)
}
func (m *SomeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeMsg.Marshal(b, m, deterministic)
}
func (m *SomeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeMsg.Merge(m, src)
}
func (m *SomeMsg) XXX_Size() int {
	return xxx_messageInfo_SomeMsg.Size(m)
}
func (m *SomeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SomeMsg proto.InternalMessageInfo

func (m *SomeMsg) GetDo() Action {
	if m != nil {
		return m.Do
	}
	return Action_ALLOW
}

func init() {
	proto.RegisterEnum("proto.Action", Action_name, Action_value)
	proto.RegisterType((*SomeMsg)(nil), "proto.SomeMsg")
}

func init() {
	proto.RegisterFile("enum.proto", fileDescriptor_13a9f1b5947140c8)
}

var fileDescriptor_13a9f1b5947140c8 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcd, 0x2b, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x66, 0xe9, 0x99, 0x25, 0x19,
	0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0xe5, 0x99, 0x25, 0xd9, 0xf9, 0xe5, 0xfa, 0xe9,
	0xf9, 0xba, 0x60, 0x49, 0xdd, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0xfc, 0xa2, 0x62, 0x7d,
	0x38, 0x13, 0xa2, 0x5d, 0xc9, 0x90, 0x8b, 0x3d, 0x38, 0x3f, 0x37, 0xd5, 0xb7, 0x38, 0x5d, 0x48,
	0x8d, 0x8b, 0x29, 0x25, 0x5f, 0x82, 0x51, 0x81, 0x51, 0x83, 0xcf, 0x88, 0x17, 0x22, 0xad, 0xe7,
	0x98, 0x5c, 0x92, 0x99, 0x9f, 0xe7, 0xc4, 0xfe, 0xe8, 0xbe, 0x3c, 0x73, 0x07, 0x23, 0x63, 0x10,
	0x53, 0x4a, 0xbe, 0x96, 0x06, 0x17, 0x1b, 0x44, 0x58, 0x88, 0x93, 0x8b, 0xd5, 0xd1, 0xc7, 0xc7,
	0x3f, 0x5c, 0x80, 0x41, 0x88, 0x83, 0x8b, 0xc5, 0xc5, 0xd5, 0x2f, 0x52, 0x80, 0x11, 0x24, 0xe8,
	0xec, 0xe1, 0xe9, 0xe3, 0x23, 0xc0, 0x94, 0xc4, 0x06, 0x36, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xee, 0xf5, 0x7f, 0x49, 0xb0, 0x00, 0x00, 0x00,
}
