// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uuid.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UUIDMsg struct {
	// user_id must be a valid version 4 UUID.
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUIDMsg) Reset()         { *m = UUIDMsg{} }
func (m *UUIDMsg) String() string { return proto.CompactTextString(m) }
func (*UUIDMsg) ProtoMessage()    {}
func (*UUIDMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b0c78c62e9a4add, []int{0}
}

func (m *UUIDMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUIDMsg.Unmarshal(m, b)
}
func (m *UUIDMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUIDMsg.Marshal(b, m, deterministic)
}
func (m *UUIDMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUIDMsg.Merge(m, src)
}
func (m *UUIDMsg) XXX_Size() int {
	return xxx_messageInfo_UUIDMsg.Size(m)
}
func (m *UUIDMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UUIDMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UUIDMsg proto.InternalMessageInfo

func (m *UUIDMsg) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*UUIDMsg)(nil), "proto.UUIDMsg")
}

func init() {
	proto.RegisterFile("uuid.proto", fileDescriptor_2b0c78c62e9a4add)
}

var fileDescriptor_2b0c78c62e9a4add = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xcd, 0x4c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x66, 0xe9, 0x99, 0x25, 0x19,
	0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0xe5, 0x99, 0x25, 0xd9, 0xf9, 0xe5, 0xfa, 0xe9,
	0xf9, 0xba, 0x60, 0x49, 0xdd, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92, 0xfc, 0xa2, 0x62, 0x7d,
	0x38, 0x13, 0xa2, 0x5d, 0x49, 0x97, 0x8b, 0x3d, 0x34, 0xd4, 0xd3, 0xc5, 0xb7, 0x38, 0x5d, 0x48,
	0x89, 0x8b, 0xbd, 0xb4, 0x38, 0xb5, 0x28, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0xd3,
	0x89, 0xf3, 0xd1, 0x7d, 0x79, 0xd6, 0x08, 0xc6, 0x09, 0x8c, 0x2c, 0x41, 0x6c, 0x20, 0x19, 0xcf,
	0x94, 0x24, 0x36, 0xb0, 0x2e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x3a, 0xb3, 0x2a,
	0x82, 0x00, 0x00, 0x00,
}
