basePath: /api/v1
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /hello/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "404":
          description: We need ID!!
          schema:
            type: string
      summary: Add a new pet to the store
swagger: "2.0"
