// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userStatus.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Session) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Session) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Session) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetSessionByUIDReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionByUIDReq) Reset()         { *m = GetSessionByUIDReq{} }
func (m *GetSessionByUIDReq) String() string { return proto.CompactTextString(m) }
func (*GetSessionByUIDReq) ProtoMessage()    {}
func (*GetSessionByUIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{1}
}

func (m *GetSessionByUIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionByUIDReq.Unmarshal(m, b)
}
func (m *GetSessionByUIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionByUIDReq.Marshal(b, m, deterministic)
}
func (m *GetSessionByUIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionByUIDReq.Merge(m, src)
}
func (m *GetSessionByUIDReq) XXX_Size() int {
	return xxx_messageInfo_GetSessionByUIDReq.Size(m)
}
func (m *GetSessionByUIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionByUIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionByUIDReq proto.InternalMessageInfo

func (m *GetSessionByUIDReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetSessionByUIDRep struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionByUIDRep) Reset()         { *m = GetSessionByUIDRep{} }
func (m *GetSessionByUIDRep) String() string { return proto.CompactTextString(m) }
func (*GetSessionByUIDRep) ProtoMessage()    {}
func (*GetSessionByUIDRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{2}
}

func (m *GetSessionByUIDRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionByUIDRep.Unmarshal(m, b)
}
func (m *GetSessionByUIDRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionByUIDRep.Marshal(b, m, deterministic)
}
func (m *GetSessionByUIDRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionByUIDRep.Merge(m, src)
}
func (m *GetSessionByUIDRep) XXX_Size() int {
	return xxx_messageInfo_GetSessionByUIDRep.Size(m)
}
func (m *GetSessionByUIDRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionByUIDRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionByUIDRep proto.InternalMessageInfo

func (m *GetSessionByUIDRep) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type GetSessionByTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionByTokenReq) Reset()         { *m = GetSessionByTokenReq{} }
func (m *GetSessionByTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetSessionByTokenReq) ProtoMessage()    {}
func (*GetSessionByTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{3}
}

func (m *GetSessionByTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionByTokenReq.Unmarshal(m, b)
}
func (m *GetSessionByTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionByTokenReq.Marshal(b, m, deterministic)
}
func (m *GetSessionByTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionByTokenReq.Merge(m, src)
}
func (m *GetSessionByTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetSessionByTokenReq.Size(m)
}
func (m *GetSessionByTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionByTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionByTokenReq proto.InternalMessageInfo

func (m *GetSessionByTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetSessionByTokenRep struct {
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionByTokenRep) Reset()         { *m = GetSessionByTokenRep{} }
func (m *GetSessionByTokenRep) String() string { return proto.CompactTextString(m) }
func (*GetSessionByTokenRep) ProtoMessage()    {}
func (*GetSessionByTokenRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{4}
}

func (m *GetSessionByTokenRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionByTokenRep.Unmarshal(m, b)
}
func (m *GetSessionByTokenRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionByTokenRep.Marshal(b, m, deterministic)
}
func (m *GetSessionByTokenRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionByTokenRep.Merge(m, src)
}
func (m *GetSessionByTokenRep) XXX_Size() int {
	return xxx_messageInfo_GetSessionByTokenRep.Size(m)
}
func (m *GetSessionByTokenRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionByTokenRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionByTokenRep proto.InternalMessageInfo

func (m *GetSessionByTokenRep) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type GetConnectorAddrReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectorAddrReq) Reset()         { *m = GetConnectorAddrReq{} }
func (m *GetConnectorAddrReq) String() string { return proto.CompactTextString(m) }
func (*GetConnectorAddrReq) ProtoMessage()    {}
func (*GetConnectorAddrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{5}
}

func (m *GetConnectorAddrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectorAddrReq.Unmarshal(m, b)
}
func (m *GetConnectorAddrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectorAddrReq.Marshal(b, m, deterministic)
}
func (m *GetConnectorAddrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectorAddrReq.Merge(m, src)
}
func (m *GetConnectorAddrReq) XXX_Size() int {
	return xxx_messageInfo_GetConnectorAddrReq.Size(m)
}
func (m *GetConnectorAddrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectorAddrReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectorAddrReq proto.InternalMessageInfo

func (m *GetConnectorAddrReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetConnectorAddrRep struct {
	ConnectorAddr        string   `protobuf:"bytes,1,opt,name=connectorAddr,proto3" json:"connectorAddr,omitempty"`
	ConnectorSessionID   uint64   `protobuf:"varint,2,opt,name=connectorSessionID,proto3" json:"connectorSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectorAddrRep) Reset()         { *m = GetConnectorAddrRep{} }
func (m *GetConnectorAddrRep) String() string { return proto.CompactTextString(m) }
func (*GetConnectorAddrRep) ProtoMessage()    {}
func (*GetConnectorAddrRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{6}
}

func (m *GetConnectorAddrRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectorAddrRep.Unmarshal(m, b)
}
func (m *GetConnectorAddrRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectorAddrRep.Marshal(b, m, deterministic)
}
func (m *GetConnectorAddrRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectorAddrRep.Merge(m, src)
}
func (m *GetConnectorAddrRep) XXX_Size() int {
	return xxx_messageInfo_GetConnectorAddrRep.Size(m)
}
func (m *GetConnectorAddrRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectorAddrRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectorAddrRep proto.InternalMessageInfo

func (m *GetConnectorAddrRep) GetConnectorAddr() string {
	if m != nil {
		return m.ConnectorAddr
	}
	return ""
}

func (m *GetConnectorAddrRep) GetConnectorSessionID() uint64 {
	if m != nil {
		return m.ConnectorSessionID
	}
	return 0
}

type UpdateConnectorAddrReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ConnectorAddr        string   `protobuf:"bytes,2,opt,name=connectorAddr,proto3" json:"connectorAddr,omitempty"`
	ConnectorSessionID   uint64   `protobuf:"varint,3,opt,name=connectorSessionID,proto3" json:"connectorSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConnectorAddrReq) Reset()         { *m = UpdateConnectorAddrReq{} }
func (m *UpdateConnectorAddrReq) String() string { return proto.CompactTextString(m) }
func (*UpdateConnectorAddrReq) ProtoMessage()    {}
func (*UpdateConnectorAddrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{7}
}

func (m *UpdateConnectorAddrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConnectorAddrReq.Unmarshal(m, b)
}
func (m *UpdateConnectorAddrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConnectorAddrReq.Marshal(b, m, deterministic)
}
func (m *UpdateConnectorAddrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConnectorAddrReq.Merge(m, src)
}
func (m *UpdateConnectorAddrReq) XXX_Size() int {
	return xxx_messageInfo_UpdateConnectorAddrReq.Size(m)
}
func (m *UpdateConnectorAddrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConnectorAddrReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConnectorAddrReq proto.InternalMessageInfo

func (m *UpdateConnectorAddrReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UpdateConnectorAddrReq) GetConnectorAddr() string {
	if m != nil {
		return m.ConnectorAddr
	}
	return ""
}

func (m *UpdateConnectorAddrReq) GetConnectorSessionID() uint64 {
	if m != nil {
		return m.ConnectorSessionID
	}
	return 0
}

type UpdateConnectorAddrRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConnectorAddrRep) Reset()         { *m = UpdateConnectorAddrRep{} }
func (m *UpdateConnectorAddrRep) String() string { return proto.CompactTextString(m) }
func (*UpdateConnectorAddrRep) ProtoMessage()    {}
func (*UpdateConnectorAddrRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{8}
}

func (m *UpdateConnectorAddrRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConnectorAddrRep.Unmarshal(m, b)
}
func (m *UpdateConnectorAddrRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConnectorAddrRep.Marshal(b, m, deterministic)
}
func (m *UpdateConnectorAddrRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConnectorAddrRep.Merge(m, src)
}
func (m *UpdateConnectorAddrRep) XXX_Size() int {
	return xxx_messageInfo_UpdateConnectorAddrRep.Size(m)
}
func (m *UpdateConnectorAddrRep) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConnectorAddrRep.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConnectorAddrRep proto.InternalMessageInfo

type NewSessionReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSessionReq) Reset()         { *m = NewSessionReq{} }
func (m *NewSessionReq) String() string { return proto.CompactTextString(m) }
func (*NewSessionReq) ProtoMessage()    {}
func (*NewSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{9}
}

func (m *NewSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSessionReq.Unmarshal(m, b)
}
func (m *NewSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSessionReq.Marshal(b, m, deterministic)
}
func (m *NewSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSessionReq.Merge(m, src)
}
func (m *NewSessionReq) XXX_Size() int {
	return xxx_messageInfo_NewSessionReq.Size(m)
}
func (m *NewSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewSessionReq proto.InternalMessageInfo

func (m *NewSessionReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewSessionReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewSessionReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewSessionReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type NewSessionRep struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSessionRep) Reset()         { *m = NewSessionRep{} }
func (m *NewSessionRep) String() string { return proto.CompactTextString(m) }
func (*NewSessionRep) ProtoMessage()    {}
func (*NewSessionRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{10}
}

func (m *NewSessionRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSessionRep.Unmarshal(m, b)
}
func (m *NewSessionRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSessionRep.Marshal(b, m, deterministic)
}
func (m *NewSessionRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSessionRep.Merge(m, src)
}
func (m *NewSessionRep) XXX_Size() int {
	return xxx_messageInfo_NewSessionRep.Size(m)
}
func (m *NewSessionRep) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSessionRep.DiscardUnknown(m)
}

var xxx_messageInfo_NewSessionRep proto.InternalMessageInfo

func (m *NewSessionRep) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RemoveSessionReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSessionReq) Reset()         { *m = RemoveSessionReq{} }
func (m *RemoveSessionReq) String() string { return proto.CompactTextString(m) }
func (*RemoveSessionReq) ProtoMessage()    {}
func (*RemoveSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{11}
}

func (m *RemoveSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSessionReq.Unmarshal(m, b)
}
func (m *RemoveSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSessionReq.Marshal(b, m, deterministic)
}
func (m *RemoveSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSessionReq.Merge(m, src)
}
func (m *RemoveSessionReq) XXX_Size() int {
	return xxx_messageInfo_RemoveSessionReq.Size(m)
}
func (m *RemoveSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSessionReq proto.InternalMessageInfo

func (m *RemoveSessionReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RemoveSessionRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSessionRep) Reset()         { *m = RemoveSessionRep{} }
func (m *RemoveSessionRep) String() string { return proto.CompactTextString(m) }
func (*RemoveSessionRep) ProtoMessage()    {}
func (*RemoveSessionRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{12}
}

func (m *RemoveSessionRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSessionRep.Unmarshal(m, b)
}
func (m *RemoveSessionRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSessionRep.Marshal(b, m, deterministic)
}
func (m *RemoveSessionRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSessionRep.Merge(m, src)
}
func (m *RemoveSessionRep) XXX_Size() int {
	return xxx_messageInfo_RemoveSessionRep.Size(m)
}
func (m *RemoveSessionRep) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSessionRep.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSessionRep proto.InternalMessageInfo

type RefreshSessionReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshSessionReq) Reset()         { *m = RefreshSessionReq{} }
func (m *RefreshSessionReq) String() string { return proto.CompactTextString(m) }
func (*RefreshSessionReq) ProtoMessage()    {}
func (*RefreshSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{13}
}

func (m *RefreshSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshSessionReq.Unmarshal(m, b)
}
func (m *RefreshSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshSessionReq.Marshal(b, m, deterministic)
}
func (m *RefreshSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshSessionReq.Merge(m, src)
}
func (m *RefreshSessionReq) XXX_Size() int {
	return xxx_messageInfo_RefreshSessionReq.Size(m)
}
func (m *RefreshSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshSessionReq proto.InternalMessageInfo

func (m *RefreshSessionReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshSessionRep struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshSessionRep) Reset()         { *m = RefreshSessionRep{} }
func (m *RefreshSessionRep) String() string { return proto.CompactTextString(m) }
func (*RefreshSessionRep) ProtoMessage()    {}
func (*RefreshSessionRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{14}
}

func (m *RefreshSessionRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshSessionRep.Unmarshal(m, b)
}
func (m *RefreshSessionRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshSessionRep.Marshal(b, m, deterministic)
}
func (m *RefreshSessionRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshSessionRep.Merge(m, src)
}
func (m *RefreshSessionRep) XXX_Size() int {
	return xxx_messageInfo_RefreshSessionRep.Size(m)
}
func (m *RefreshSessionRep) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshSessionRep.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshSessionRep proto.InternalMessageInfo

func (m *RefreshSessionRep) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshSessionRep) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type UserConnectedReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConnectorAddress     string   `protobuf:"bytes,2,opt,name=connectorAddress,proto3" json:"connectorAddress,omitempty"`
	ConnectorSessionID   uint64   `protobuf:"varint,3,opt,name=connectorSessionID,proto3" json:"connectorSessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserConnectedReq) Reset()         { *m = UserConnectedReq{} }
func (m *UserConnectedReq) String() string { return proto.CompactTextString(m) }
func (*UserConnectedReq) ProtoMessage()    {}
func (*UserConnectedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{15}
}

func (m *UserConnectedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserConnectedReq.Unmarshal(m, b)
}
func (m *UserConnectedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserConnectedReq.Marshal(b, m, deterministic)
}
func (m *UserConnectedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserConnectedReq.Merge(m, src)
}
func (m *UserConnectedReq) XXX_Size() int {
	return xxx_messageInfo_UserConnectedReq.Size(m)
}
func (m *UserConnectedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserConnectedReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserConnectedReq proto.InternalMessageInfo

func (m *UserConnectedReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserConnectedReq) GetConnectorAddress() string {
	if m != nil {
		return m.ConnectorAddress
	}
	return ""
}

func (m *UserConnectedReq) GetConnectorSessionID() uint64 {
	if m != nil {
		return m.ConnectorSessionID
	}
	return 0
}

type UserConnectedRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserConnectedRep) Reset()         { *m = UserConnectedRep{} }
func (m *UserConnectedRep) String() string { return proto.CompactTextString(m) }
func (*UserConnectedRep) ProtoMessage()    {}
func (*UserConnectedRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{16}
}

func (m *UserConnectedRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserConnectedRep.Unmarshal(m, b)
}
func (m *UserConnectedRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserConnectedRep.Marshal(b, m, deterministic)
}
func (m *UserConnectedRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserConnectedRep.Merge(m, src)
}
func (m *UserConnectedRep) XXX_Size() int {
	return xxx_messageInfo_UserConnectedRep.Size(m)
}
func (m *UserConnectedRep) XXX_DiscardUnknown() {
	xxx_messageInfo_UserConnectedRep.DiscardUnknown(m)
}

var xxx_messageInfo_UserConnectedRep proto.InternalMessageInfo

type UserDisonnectedReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConnectorAddress     string   `protobuf:"bytes,2,opt,name=connectorAddress,proto3" json:"connectorAddress,omitempty"`
	ConnectorSessionID   uint64   `protobuf:"varint,3,opt,name=connectorSessionID,proto3" json:"connectorSessionID,omitempty"`
	OnlineTime           int32    `protobuf:"varint,4,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDisonnectedReq) Reset()         { *m = UserDisonnectedReq{} }
func (m *UserDisonnectedReq) String() string { return proto.CompactTextString(m) }
func (*UserDisonnectedReq) ProtoMessage()    {}
func (*UserDisonnectedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{17}
}

func (m *UserDisonnectedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDisonnectedReq.Unmarshal(m, b)
}
func (m *UserDisonnectedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDisonnectedReq.Marshal(b, m, deterministic)
}
func (m *UserDisonnectedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDisonnectedReq.Merge(m, src)
}
func (m *UserDisonnectedReq) XXX_Size() int {
	return xxx_messageInfo_UserDisonnectedReq.Size(m)
}
func (m *UserDisonnectedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDisonnectedReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserDisonnectedReq proto.InternalMessageInfo

func (m *UserDisonnectedReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserDisonnectedReq) GetConnectorAddress() string {
	if m != nil {
		return m.ConnectorAddress
	}
	return ""
}

func (m *UserDisonnectedReq) GetConnectorSessionID() uint64 {
	if m != nil {
		return m.ConnectorSessionID
	}
	return 0
}

func (m *UserDisonnectedReq) GetOnlineTime() int32 {
	if m != nil {
		return m.OnlineTime
	}
	return 0
}

type UserDisonnectedRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDisonnectedRep) Reset()         { *m = UserDisonnectedRep{} }
func (m *UserDisonnectedRep) String() string { return proto.CompactTextString(m) }
func (*UserDisonnectedRep) ProtoMessage()    {}
func (*UserDisonnectedRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{18}
}

func (m *UserDisonnectedRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDisonnectedRep.Unmarshal(m, b)
}
func (m *UserDisonnectedRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDisonnectedRep.Marshal(b, m, deterministic)
}
func (m *UserDisonnectedRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDisonnectedRep.Merge(m, src)
}
func (m *UserDisonnectedRep) XXX_Size() int {
	return xxx_messageInfo_UserDisonnectedRep.Size(m)
}
func (m *UserDisonnectedRep) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDisonnectedRep.DiscardUnknown(m)
}

var xxx_messageInfo_UserDisonnectedRep proto.InternalMessageInfo

type RemoveSessionByUIDReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSessionByUIDReq) Reset()         { *m = RemoveSessionByUIDReq{} }
func (m *RemoveSessionByUIDReq) String() string { return proto.CompactTextString(m) }
func (*RemoveSessionByUIDReq) ProtoMessage()    {}
func (*RemoveSessionByUIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{19}
}

func (m *RemoveSessionByUIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSessionByUIDReq.Unmarshal(m, b)
}
func (m *RemoveSessionByUIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSessionByUIDReq.Marshal(b, m, deterministic)
}
func (m *RemoveSessionByUIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSessionByUIDReq.Merge(m, src)
}
func (m *RemoveSessionByUIDReq) XXX_Size() int {
	return xxx_messageInfo_RemoveSessionByUIDReq.Size(m)
}
func (m *RemoveSessionByUIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSessionByUIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSessionByUIDReq proto.InternalMessageInfo

func (m *RemoveSessionByUIDReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type RemoveSessionByUIDRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSessionByUIDRep) Reset()         { *m = RemoveSessionByUIDRep{} }
func (m *RemoveSessionByUIDRep) String() string { return proto.CompactTextString(m) }
func (*RemoveSessionByUIDRep) ProtoMessage()    {}
func (*RemoveSessionByUIDRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{20}
}

func (m *RemoveSessionByUIDRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSessionByUIDRep.Unmarshal(m, b)
}
func (m *RemoveSessionByUIDRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSessionByUIDRep.Marshal(b, m, deterministic)
}
func (m *RemoveSessionByUIDRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSessionByUIDRep.Merge(m, src)
}
func (m *RemoveSessionByUIDRep) XXX_Size() int {
	return xxx_messageInfo_RemoveSessionByUIDRep.Size(m)
}
func (m *RemoveSessionByUIDRep) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSessionByUIDRep.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSessionByUIDRep proto.InternalMessageInfo

type GetUserIDByTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDByTokenReq) Reset()         { *m = GetUserIDByTokenReq{} }
func (m *GetUserIDByTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetUserIDByTokenReq) ProtoMessage()    {}
func (*GetUserIDByTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{21}
}

func (m *GetUserIDByTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDByTokenReq.Unmarshal(m, b)
}
func (m *GetUserIDByTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDByTokenReq.Marshal(b, m, deterministic)
}
func (m *GetUserIDByTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDByTokenReq.Merge(m, src)
}
func (m *GetUserIDByTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetUserIDByTokenReq.Size(m)
}
func (m *GetUserIDByTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDByTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDByTokenReq proto.InternalMessageInfo

func (m *GetUserIDByTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUserIDByTokenRep struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIDByTokenRep) Reset()         { *m = GetUserIDByTokenRep{} }
func (m *GetUserIDByTokenRep) String() string { return proto.CompactTextString(m) }
func (*GetUserIDByTokenRep) ProtoMessage()    {}
func (*GetUserIDByTokenRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4d6af95c4da3392, []int{22}
}

func (m *GetUserIDByTokenRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIDByTokenRep.Unmarshal(m, b)
}
func (m *GetUserIDByTokenRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIDByTokenRep.Marshal(b, m, deterministic)
}
func (m *GetUserIDByTokenRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIDByTokenRep.Merge(m, src)
}
func (m *GetUserIDByTokenRep) XXX_Size() int {
	return xxx_messageInfo_GetUserIDByTokenRep.Size(m)
}
func (m *GetUserIDByTokenRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIDByTokenRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIDByTokenRep proto.InternalMessageInfo

func (m *GetUserIDByTokenRep) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*Session)(nil), "pb.Session")
	proto.RegisterType((*GetSessionByUIDReq)(nil), "pb.GetSessionByUIDReq")
	proto.RegisterType((*GetSessionByUIDRep)(nil), "pb.GetSessionByUIDRep")
	proto.RegisterType((*GetSessionByTokenReq)(nil), "pb.GetSessionByTokenReq")
	proto.RegisterType((*GetSessionByTokenRep)(nil), "pb.GetSessionByTokenRep")
	proto.RegisterType((*GetConnectorAddrReq)(nil), "pb.GetConnectorAddrReq")
	proto.RegisterType((*GetConnectorAddrRep)(nil), "pb.GetConnectorAddrRep")
	proto.RegisterType((*UpdateConnectorAddrReq)(nil), "pb.UpdateConnectorAddrReq")
	proto.RegisterType((*UpdateConnectorAddrRep)(nil), "pb.UpdateConnectorAddrRep")
	proto.RegisterType((*NewSessionReq)(nil), "pb.NewSessionReq")
	proto.RegisterType((*NewSessionRep)(nil), "pb.NewSessionRep")
	proto.RegisterType((*RemoveSessionReq)(nil), "pb.RemoveSessionReq")
	proto.RegisterType((*RemoveSessionRep)(nil), "pb.RemoveSessionRep")
	proto.RegisterType((*RefreshSessionReq)(nil), "pb.RefreshSessionReq")
	proto.RegisterType((*RefreshSessionRep)(nil), "pb.RefreshSessionRep")
	proto.RegisterType((*UserConnectedReq)(nil), "pb.UserConnectedReq")
	proto.RegisterType((*UserConnectedRep)(nil), "pb.UserConnectedRep")
	proto.RegisterType((*UserDisonnectedReq)(nil), "pb.UserDisonnectedReq")
	proto.RegisterType((*UserDisonnectedRep)(nil), "pb.UserDisonnectedRep")
	proto.RegisterType((*RemoveSessionByUIDReq)(nil), "pb.RemoveSessionByUIDReq")
	proto.RegisterType((*RemoveSessionByUIDRep)(nil), "pb.RemoveSessionByUIDRep")
	proto.RegisterType((*GetUserIDByTokenReq)(nil), "pb.GetUserIDByTokenReq")
	proto.RegisterType((*GetUserIDByTokenRep)(nil), "pb.GetUserIDByTokenRep")
}

func init() { proto.RegisterFile("userStatus.proto", fileDescriptor_d4d6af95c4da3392) }

var fileDescriptor_d4d6af95c4da3392 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0x26, 0x51, 0xa7, 0x4a, 0xeb, 0x4c, 0xd3, 0xd4, 0xec, 0x01, 0x55, 0x2b, 0x4a,
	0xc3, 0x87, 0x72, 0x28, 0xdc, 0x50, 0x25, 0x20, 0x11, 0x55, 0x24, 0x04, 0x95, 0xdb, 0x1c, 0x39,
	0x24, 0xf1, 0xa2, 0x5a, 0x25, 0xf6, 0xd6, 0x76, 0x40, 0xdc, 0x38, 0xf5, 0xb7, 0xf0, 0x33, 0xd1,
	0xd8, 0x4e, 0x6a, 0x7b, 0xd7, 0x4d, 0x39, 0x20, 0x6e, 0xde, 0xb7, 0x6f, 0x76, 0xde, 0xee, 0xcc,
	0x3c, 0x19, 0xac, 0x45, 0x24, 0xc2, 0x8b, 0x78, 0x12, 0x2f, 0xa2, 0xbe, 0x0c, 0x83, 0x38, 0x40,
	0x53, 0x4e, 0xf9, 0x17, 0x68, 0x5e, 0x88, 0x28, 0xf2, 0x02, 0x1f, 0x77, 0xc0, 0xf4, 0x5c, 0xdb,
	0x38, 0x34, 0x7a, 0x75, 0xc7, 0xf4, 0x5c, 0x44, 0xd8, 0xf4, 0x27, 0x73, 0x61, 0x9b, 0x87, 0x46,
	0x6f, 0xcb, 0x49, 0xbe, 0xd1, 0x86, 0xe6, 0x3b, 0xd7, 0x0d, 0x45, 0x14, 0xd9, 0xb5, 0x04, 0x5e,
	0x2e, 0xb1, 0x03, 0xf5, 0xf3, 0xab, 0xc0, 0x17, 0xf6, 0x66, 0x82, 0xa7, 0x0b, 0xfe, 0x14, 0xf0,
	0x4c, 0xc4, 0x59, 0x86, 0xf7, 0x3f, 0xc7, 0xa3, 0xa1, 0x23, 0x6e, 0xd0, 0x82, 0xda, 0x22, 0x4b,
	0x55, 0x73, 0xe8, 0x93, 0xbf, 0xd1, 0xf0, 0x24, 0x1e, 0x41, 0x33, 0x4a, 0xa1, 0x84, 0xbb, 0x7d,
	0xb2, 0xdd, 0x97, 0xd3, 0x7e, 0xc6, 0x72, 0x96, 0x7b, 0xfc, 0x25, 0x74, 0xf2, 0xc1, 0x97, 0xc1,
	0xb5, 0xf0, 0x29, 0x4d, 0x07, 0xea, 0x31, 0x7d, 0x27, 0xc1, 0x5b, 0x4e, 0xba, 0xe0, 0xa7, 0x5a,
	0xf6, 0x83, 0x93, 0x1d, 0xc3, 0xde, 0x99, 0x88, 0x07, 0x81, 0xef, 0x8b, 0x59, 0x1c, 0x84, 0x74,
	0x7d, 0xfd, 0x95, 0xae, 0x75, 0x44, 0x89, 0x4f, 0xa0, 0x35, 0xcb, 0x63, 0x99, 0xb8, 0x22, 0x88,
	0x7d, 0xc0, 0x15, 0x90, 0x49, 0x18, 0x0d, 0x93, 0x4a, 0x6c, 0x3a, 0x9a, 0x1d, 0xfe, 0xcb, 0x80,
	0xee, 0x58, 0xba, 0x93, 0x58, 0xac, 0x57, 0xa6, 0x4a, 0x30, 0x1f, 0x2e, 0xa1, 0x56, 0x29, 0xc1,
	0xae, 0x50, 0x20, 0xf9, 0x0c, 0x5a, 0x9f, 0xc4, 0x8f, 0xe5, 0x4b, 0x8a, 0x9b, 0x7f, 0xd2, 0x69,
	0x47, 0xc5, 0x24, 0xb2, 0xa2, 0xfa, 0x3d, 0xb0, 0x1c, 0x31, 0x0f, 0xbe, 0x8b, 0x9c, 0x1c, 0x3d,
	0x13, 0x15, 0xa6, 0xe4, 0xcf, 0xa0, 0xed, 0x88, 0xaf, 0xa1, 0x88, 0xae, 0xd6, 0x86, 0x9f, 0xab,
	0xd4, 0x0a, 0x4d, 0xf9, 0xce, 0x33, 0xef, 0xe9, 0xbc, 0x5b, 0x03, 0xac, 0x71, 0x24, 0xc2, 0xec,
	0x7d, 0x85, 0x4b, 0xc9, 0xbb, 0xd0, 0xa0, 0xb9, 0x1e, 0x0d, 0xb3, 0x02, 0x67, 0x2b, 0x7c, 0x0e,
	0x56, 0xa1, 0x9c, 0xf4, 0x8e, 0xe9, 0xf3, 0x2a, 0xf8, 0x5f, 0x57, 0x1a, 0x15, 0x1d, 0x92, 0xff,
	0x36, 0x00, 0x09, 0x1c, 0x7a, 0xd1, 0x7f, 0x96, 0x87, 0x8f, 0x01, 0x02, 0xff, 0x9b, 0xe7, 0x8b,
	0x4b, 0x6f, 0x9e, 0x36, 0x49, 0xdd, 0xc9, 0x21, 0xbc, 0xa3, 0x51, 0x4a, 0xa5, 0xdd, 0x2f, 0x94,
	0xfb, 0x1e, 0xb3, 0x3a, 0xd0, 0x53, 0x25, 0x7f, 0x91, 0x8c, 0xfc, 0x38, 0xb9, 0xe2, 0x5a, 0x1f,
	0x3a, 0xd6, 0x91, 0xa5, 0x9a, 0xee, 0xe4, 0xb6, 0x01, 0x30, 0x5e, 0x79, 0x37, 0x0e, 0x60, 0xb7,
	0x64, 0x95, 0xd8, 0xa5, 0x7e, 0x51, 0x7d, 0x96, 0xe9, 0x71, 0xc9, 0x37, 0x70, 0x04, 0x6d, 0xc5,
	0x04, 0xd1, 0x2e, 0xd3, 0x97, 0x37, 0x60, 0x55, 0x3b, 0x74, 0xd4, 0x07, 0xb0, 0xca, 0x3e, 0x87,
	0x07, 0x19, 0xbf, 0x6c, 0x46, 0xac, 0x62, 0x83, 0xce, 0xf9, 0x0c, 0x7b, 0x1a, 0xff, 0x40, 0x46,
	0x11, 0x7a, 0x6b, 0x63, 0xd5, 0x7b, 0x74, 0xe0, 0x6b, 0x80, 0x3b, 0x47, 0xc0, 0x36, 0x71, 0x0b,
	0x36, 0xc4, 0x14, 0x88, 0xa2, 0x4e, 0xa1, 0x55, 0x28, 0x2e, 0x76, 0x88, 0x55, 0xf6, 0x0c, 0xa6,
	0x43, 0x29, 0xfc, 0x2d, 0xec, 0x14, 0xc7, 0x1e, 0xf7, 0x53, 0x66, 0xc9, 0x35, 0x98, 0x16, 0xce,
	0x04, 0x14, 0xa6, 0x2b, 0x15, 0x50, 0x1e, 0x7c, 0xa6, 0x43, 0x29, 0x7c, 0x00, 0xbb, 0xa5, 0xee,
	0x4e, 0xdb, 0x43, 0x1d, 0x4e, 0xa6, 0xc7, 0xe9, 0x90, 0x8f, 0x80, 0x6a, 0x87, 0xe3, 0x23, 0xe5,
	0xce, 0xab, 0x4e, 0xab, 0xdc, 0xba, 0xeb, 0x90, 0x42, 0xa7, 0xaf, 0x3a, 0xa4, 0x3c, 0x2c, 0xac,
	0x62, 0x43, 0xf2, 0x8d, 0x69, 0x23, 0xf9, 0x6d, 0x79, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xdc,
	0xc1, 0x87, 0x92, 0xca, 0x08, 0x00, 0x00,
}
