// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserReq) Reset()         { *m = ModifyUserReq{} }
func (m *ModifyUserReq) String() string { return proto.CompactTextString(m) }
func (*ModifyUserReq) ProtoMessage()    {}
func (*ModifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ModifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserReq.Unmarshal(m, b)
}
func (m *ModifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserReq.Marshal(b, m, deterministic)
}
func (m *ModifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserReq.Merge(m, src)
}
func (m *ModifyUserReq) XXX_Size() int {
	return xxx_messageInfo_ModifyUserReq.Size(m)
}
func (m *ModifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserReq proto.InternalMessageInfo

func (m *ModifyUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModifyUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ModifyUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ModifyUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserRep) Reset()         { *m = ModifyUserRep{} }
func (m *ModifyUserRep) String() string { return proto.CompactTextString(m) }
func (*ModifyUserRep) ProtoMessage()    {}
func (*ModifyUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *ModifyUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserRep.Unmarshal(m, b)
}
func (m *ModifyUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserRep.Marshal(b, m, deterministic)
}
func (m *ModifyUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserRep.Merge(m, src)
}
func (m *ModifyUserRep) XXX_Size() int {
	return xxx_messageInfo_ModifyUserRep.Size(m)
}
func (m *ModifyUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserRep proto.InternalMessageInfo

type SelectUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserReq) Reset()         { *m = SelectUserReq{} }
func (m *SelectUserReq) String() string { return proto.CompactTextString(m) }
func (*SelectUserReq) ProtoMessage()    {}
func (*SelectUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SelectUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserReq.Unmarshal(m, b)
}
func (m *SelectUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserReq.Marshal(b, m, deterministic)
}
func (m *SelectUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserReq.Merge(m, src)
}
func (m *SelectUserReq) XXX_Size() int {
	return xxx_messageInfo_SelectUserReq.Size(m)
}
func (m *SelectUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserReq proto.InternalMessageInfo

func (m *SelectUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectUserRep struct {
	Users                *User    `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectUserRep) Reset()         { *m = SelectUserRep{} }
func (m *SelectUserRep) String() string { return proto.CompactTextString(m) }
func (*SelectUserRep) ProtoMessage()    {}
func (*SelectUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SelectUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectUserRep.Unmarshal(m, b)
}
func (m *SelectUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectUserRep.Marshal(b, m, deterministic)
}
func (m *SelectUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectUserRep.Merge(m, src)
}
func (m *SelectUserRep) XXX_Size() int {
	return xxx_messageInfo_SelectUserRep.Size(m)
}
func (m *SelectUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_SelectUserRep proto.InternalMessageInfo

func (m *SelectUserRep) GetUsers() *User {
	if m != nil {
		return m.Users
	}
	return nil
}

type DeletetUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletetUserReq) Reset()         { *m = DeletetUserReq{} }
func (m *DeletetUserReq) String() string { return proto.CompactTextString(m) }
func (*DeletetUserReq) ProtoMessage()    {}
func (*DeletetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DeletetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletetUserReq.Unmarshal(m, b)
}
func (m *DeletetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletetUserReq.Marshal(b, m, deterministic)
}
func (m *DeletetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletetUserReq.Merge(m, src)
}
func (m *DeletetUserReq) XXX_Size() int {
	return xxx_messageInfo_DeletetUserReq.Size(m)
}
func (m *DeletetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletetUserReq proto.InternalMessageInfo

func (m *DeletetUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletetUserRep struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletetUserRep) Reset()         { *m = DeletetUserRep{} }
func (m *DeletetUserRep) String() string { return proto.CompactTextString(m) }
func (*DeletetUserRep) ProtoMessage()    {}
func (*DeletetUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *DeletetUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletetUserRep.Unmarshal(m, b)
}
func (m *DeletetUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletetUserRep.Marshal(b, m, deterministic)
}
func (m *DeletetUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletetUserRep.Merge(m, src)
}
func (m *DeletetUserRep) XXX_Size() int {
	return xxx_messageInfo_DeletetUserRep.Size(m)
}
func (m *DeletetUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletetUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_DeletetUserRep proto.InternalMessageInfo

type InsertUserReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserReq) Reset()         { *m = InsertUserReq{} }
func (m *InsertUserReq) String() string { return proto.CompactTextString(m) }
func (*InsertUserReq) ProtoMessage()    {}
func (*InsertUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *InsertUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserReq.Unmarshal(m, b)
}
func (m *InsertUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserReq.Marshal(b, m, deterministic)
}
func (m *InsertUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserReq.Merge(m, src)
}
func (m *InsertUserReq) XXX_Size() int {
	return xxx_messageInfo_InsertUserReq.Size(m)
}
func (m *InsertUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserReq proto.InternalMessageInfo

func (m *InsertUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type InsertUserRep struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertUserRep) Reset()         { *m = InsertUserRep{} }
func (m *InsertUserRep) String() string { return proto.CompactTextString(m) }
func (*InsertUserRep) ProtoMessage()    {}
func (*InsertUserRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *InsertUserRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertUserRep.Unmarshal(m, b)
}
func (m *InsertUserRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertUserRep.Marshal(b, m, deterministic)
}
func (m *InsertUserRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertUserRep.Merge(m, src)
}
func (m *InsertUserRep) XXX_Size() int {
	return xxx_messageInfo_InsertUserRep.Size(m)
}
func (m *InsertUserRep) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertUserRep.DiscardUnknown(m)
}

var xxx_messageInfo_InsertUserRep proto.InternalMessageInfo

func (m *InsertUserRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertUserRep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InsertUserRep) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InsertUserRep) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*ModifyUserReq)(nil), "pb.ModifyUserReq")
	proto.RegisterType((*ModifyUserRep)(nil), "pb.ModifyUserRep")
	proto.RegisterType((*SelectUserReq)(nil), "pb.SelectUserReq")
	proto.RegisterType((*SelectUserRep)(nil), "pb.SelectUserRep")
	proto.RegisterType((*DeletetUserReq)(nil), "pb.DeletetUserReq")
	proto.RegisterType((*DeletetUserRep)(nil), "pb.DeletetUserRep")
	proto.RegisterType((*InsertUserReq)(nil), "pb.InsertUserReq")
	proto.RegisterType((*InsertUserRep)(nil), "pb.InsertUserRep")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x2f, 0xf1, 0xe2, 0x9f, 0x09, 0x77, 0xea, 0x60, 0xb1, 0xa4, 0xd0, 0xb0, 0xd5, 0x55,
	0x11, 0xce, 0x03, 0x6b, 0xc1, 0xc6, 0x42, 0x90, 0x1c, 0x36, 0x76, 0x26, 0x3b, 0x62, 0xe0, 0x4c,
	0xc6, 0xdd, 0x28, 0xf8, 0x8d, 0xfd, 0x18, 0xb2, 0x1b, 0x25, 0xee, 0x85, 0x2b, 0xd3, 0x65, 0x5f,
	0xde, 0xec, 0x8f, 0x79, 0x33, 0x0b, 0xf0, 0x61, 0x48, 0x67, 0xac, 0x9b, 0xb6, 0xc1, 0x90, 0x0b,
	0xf9, 0x04, 0xd3, 0x47, 0x43, 0x1a, 0xe7, 0x10, 0x56, 0x4a, 0x04, 0x69, 0xb0, 0x88, 0xf2, 0xb0,
	0x52, 0x88, 0x30, 0xad, 0x9f, 0xdf, 0x48, 0x84, 0x69, 0xb0, 0x38, 0xca, 0xdd, 0x37, 0x0a, 0x38,
	0xb8, 0x51, 0x4a, 0x93, 0x31, 0x62, 0xcf, 0xc9, 0x7f, 0x47, 0x3c, 0x83, 0xe8, 0xe1, 0xb5, 0xa9,
	0x49, 0x4c, 0x9d, 0xde, 0x1d, 0x64, 0x09, 0xb3, 0xfb, 0x46, 0x55, 0x2f, 0x5f, 0x96, 0x90, 0xd3,
	0xfb, 0x28, 0x90, 0x63, 0x1f, 0xc2, 0xf2, 0x02, 0x66, 0x6b, 0xda, 0x50, 0xd9, 0xee, 0xa0, 0xca,
	0x4b, 0xdf, 0xc0, 0x78, 0x0e, 0x91, 0x4d, 0xc5, 0x38, 0x4f, 0xbc, 0x3c, 0xcc, 0xb8, 0xc8, 0xdc,
	0xbf, 0x4e, 0x96, 0x29, 0xcc, 0x6f, 0x69, 0x43, 0x2d, 0xed, 0xbc, 0xf2, 0x64, 0xcb, 0xc1, 0xb6,
	0xf7, 0xbb, 0xda, 0x90, 0x6e, 0xc7, 0xec, 0x7d, 0x0b, 0xc2, 0x63, 0x40, 0x96, 0xdf, 0x01, 0xc4,
	0xf6, 0xfe, 0x35, 0xe9, 0xcf, 0xaa, 0x24, 0x5c, 0x01, 0xf4, 0x50, 0x3c, 0xb5, 0x61, 0x79, 0x9d,
	0x26, 0x03, 0x89, 0xe5, 0x04, 0xaf, 0x21, 0xfe, 0x97, 0x10, 0xa2, 0xf5, 0xf8, 0xa1, 0x26, 0x43,
	0xcd, 0x16, 0xae, 0x00, 0xfa, 0x69, 0x75, 0x38, 0x6f, 0xbc, 0xc9, 0x40, 0xfa, 0xad, 0xea, 0xb7,
	0xa2, 0xab, 0xf2, 0x56, 0x31, 0x19, 0x48, 0x2c, 0x27, 0xc5, 0xbe, 0x7b, 0x17, 0x57, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xda, 0x06, 0x39, 0x51, 0x25, 0x03, 0x00, 0x00,
}
